### ISSUE TITLE
import java.util.Iterator missing on NOC_4_04_SystemofSystems_c

### ISSUE THREAD

**Issue by villares** [shiffman/The-Nature-of-Code-Examples#30]
I'm a newbie, but maybe `import java.util.Iterator;` should be added to the _NOC_4_04_SystemofSystems_c_ example found on Processing 2.0 so it can work out of the box.

**Comment by JackLinMaker** [comment]
this is the error i get after i import the Iterator library:expecting EOF, found 'import'
