### ISSUE TITLE
examples with p5.js 

### ISSUE THREAD

**Issue by paulmason** [shiffman/The-Nature-of-Code-Examples#57]
Hey Daniel, just starting your book, really looking forward to getting into it!

I was just curious to see if you had any plans of creating a set of javascript examples - so that we can follow along using p5.js?

**Comment by shiffman** [comment]
Hello!  All the examples are in fact ported here!

https://github.com/shiffman/The-Nature-of-Code-Examples-p5.js

Other ports are listed on the [readme](https://github.com/shiffman/The-Nature-of-Code-Examples/blob/master/README.md) and as soon as [this is settled](https://github.com/shiffman/The-Nature-of-Code/issues/46) I plan on rewriting a JS version of the book itself!

**Comment by hjoaco** [comment]
Excellent :D

**Comment by paulmason** [comment]
Awesome, thanks so much!
